apiVersion: v1
kind: Pod
metadata:
  name: readiness-demo
  labels:
    app: readiness        # Label for Service to find
spec:
  containers:
  - name: app
    image: nginx
    ports:
    - containerPort: 80
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/ready
      initialDelaySeconds: 5
      periodSeconds: 5
