apiVersion: v1
kind: Pod
metadata:
  name: svc-test-dns
  namespace: service-namespace
spec:
  containers:
    - name: busybox-svc
      image: curlimages/curl:latest
      command:
        - sleep
        - '3600'
