apiVersion: v1
kind: Pod
metadata:
  name: pod-gpu-required
spec:
  containers:
  - name: app
    image: busybox
    command: ['sh', '-c', 'echo Needs GPU node && sleep 3600']
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: gpu
            operator: Exists      # Node must have 'gpu' label (any value!)
