apiVersion: v1
kind: Pod
metadata:
  name: pod-must-and-prefer
spec:
  containers:
  - name: nginx
    image: nginx
  affinity:
    nodeAffinity:
      # MUST be Linux
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/os
            operator: In
            values:
            - linux
      
      # PREFER SSD
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 80
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
