apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitor-all-nodes
spec:
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
      containers:
      - name: monitor
        image: busybox
        command: ['sh', '-c', 'echo Monitoring $(hostname) && sleep 3600']
